# pre-commit hooks require a user to have installed `pre-commit`:
#   $ brew install pre-commit
# Then install the hooks within the repo:
#   $ cd /PATH/TO/base-python3 (or whatever your package is located)
#   $ pre-commit install
# You only need to run the `install` once per repo

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # Runs type checking. See pyproject.toml for config options.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args:
          [
            "--disable-error-code=no-redef",
            "--disable-error-code=override",
            "--ignore-missing-imports",
            "--explicit-package-bases",
          ]
        additional_dependencies: ["types-pyyaml", "types-requests"]
        exclude: "tests"
        ignore: "tests"
